#!/usr/bin/env python3
"""Dev-time helper: converts the Linux console VGA 8x8 font (PSF) into
NASM data (src/font.inc). The game itself never runs Python; this only
regenerates a data file that is committed to the repo."""
import gzip, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-VGA8.psf.gz"
data = gzip.open(src).read()
assert data[0:2] == b"\x36\x04", "expected PSF1"
mode, h = data[2], data[3]
n = 512 if mode & 1 else 256
glyphs = [data[4 + i * h: 4 + (i + 1) * h] for i in range(n)]
table = data[4 + n * h:]
umap = {}
if mode & 2:
    i, g = 0, 0
    while g < n and i + 1 < len(table):
        u = table[i] | table[i + 1] << 8
        i += 2
        if u == 0xFFFF:
            g += 1
        elif u != 0xFFFE and u not in umap:
            umap[u] = g
out = ["; 8x8 VGA font, ASCII 0..127 (generated by tools/mkfont.py)", "font8x8:"]
for c in range(128):
    g = glyphs[umap.get(c, umap.get(0x20, 0))] if c >= 32 else bytes(8)
    out.append("    db " + ",".join("0x%02X" % b for b in g[:8]) + "  ; %d" % c)
open(sys.argv[2] if len(sys.argv) > 2 else "src/font.inc", "w").write("\n".join(out) + "\n")
